name: zrp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.21.*
  - pandas=1.2.5
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - xgboost=1.0.2
  - category_encoders=2.3.0
  - feature_engine=1.2.0
  - joblib=1.2.0
  - fastparquet=0.7.1
  - pyarrow=7.0.0
  - censusdata=1.15
  - plac=1.3.4
  - tqdm=4.46.0
  - pycm=3.3

  - pip:
      - surgeo==1.1.2
